### ISSUE TITLE
Couple of typescript related issues

### ISSUE THREAD

**Issue by sanjade** [qmhc/vite-plugin-dts#3] opened 2021-06-08 14:31 UTC
I'm using vite for my vanilla typescript project along with this plugin. I found few bugs with this library,

- When I build the project with this plugin, it leaves the converted javascript files in the disk as you can see in the project.

<img width="239" alt="Screen Shot 2021-06-08 at 7 46 35 PM" src="https://user-images.githubusercontent.com/31353695/121199199-7645d300-c892-11eb-8031-365e9854259a.png">

- If I use a non relative path like `/@/`, then the emitted declarations includes incorrect path. For example,

I have `constants.ts`,
```
export enum Color {
    Red,
    Blue,
    Green
}

export const colors = new Array<Color>(Color.Red, Color.Blue, Color.Green)
```

And in `main.ts` I have following,
```
import { Color } from "/@/constants"

export default function viteProject(): Color {
    console.log(Color.Red)
    return Color.Red
}
```

Then the emitted declaration file has `src/constants` which is an incorrect path,
```
import { Color } from 'src/constants';
export default function viteProject(): Color;
```

Here's the source code: https://github.com/sanjade/js-bug

**Comment by qmhc** [comment] 2021-06-08 15:33
Thanks for using this plugin.

For the first point, is not a bug in this plugin, because you used `tsc` without `--noEmit` parameter.

The second point strictly is not a bug.

The reason is when all files are in one directory and without `rootDir` config in `tsconfig.json`, the root directory in ts will be inferred to that only one directory, so incorrect path calculation occurred.

Currently you can add `{ "rootDir": "." }` to your `tsconfig.json` solve this problem succinctly.

**Comment by sanjade** [comment] 2021-06-09 02:20
@qmhc For the first point, do you mean in package.json I should do `"build": "tsc --noEmit && vite build"`? Because I did that and it gives me the following error,
```
tsconfig.json:9:9 - error TS5053: Option 'emitDeclarationOnly' cannot be specified with option 'noEmit'.

9         "emitDeclarationOnly": true,
```

Regarding the second point the dts file is generated as `main.d.ts`. Shouldn't it be `index.d.ts`? Because typescript complains that there are no types for the lib.

<img width="677" alt="Screen Shot 2021-06-09 at 8 02 42 AM" src="https://user-images.githubusercontent.com/31353695/121282363-13d3ed80-c8f9-11eb-9245-ae9a9b9adcb5.png">

**Comment by qmhc** [comment] 2021-06-09 08:03
@sanjade If you only want to check your typescript you needn't add `emitDeclarationOnly` option.

The `.d.ts` files named by the source files name, for your situation I think you should add `types` option in your lib `package.json` to specify the entry of type analysis, just like `main` option.

```json
{
  "main": "dist/viteproject.cjs.js",
  "types": "dist/main.d.ts",
}
```

I recommend you to try `@microsoft/api-extractor` if you want to bundle all declaration in one file.

> The `staticImport` option is for using `@microsoft/api-extractor`.

**Closed** 2021-06-09 09:11 UTC
Labels: bug

**Comment by sanjade** [comment] 2021-06-09 11:44
Thanks a lot!
